services:
  redis:
    image: redis:7-alpine
    command: ["redis-server", "--appendonly", "yes"]
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
  postgres:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: jobful
      POSTGRES_USER: jobful
      POSTGRES_PASSWORD: jobful_dev
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
  events-postgres:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: jobful_events
      POSTGRES_USER: jobful_events
      POSTGRES_PASSWORD: jobful_events_dev
    ports:
      - "5433:5432"
    volumes:
      - events-postgres-data:/var/lib/postgresql/data

volumes:
  redis-data:
  postgres-data:
  events-postgres-data:
